name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    name: Build and Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Derive appropriate SHAs for base and head for nx affected commands
        uses: nrwl/nx-set-shas@v4

      - name: Run build on affected projects
        run: npx nx affected --target=build --parallel=3 --exclude=@jakub007d/react-renderer-demo
        continue-on-error: false

      - name: Run lint on affected projects
        run: npx nx affected --target=lint --parallel=3
        continue-on-error: false

      - name: Run typecheck on affected projects
        run: npx nx affected --target=typecheck --parallel=3
        continue-on-error: false

      # Dry-run release on pull requests
      - name: Run Nx release dry-run (PR)
        if: github.event_name == 'pull_request'
        id: nx-release-dry-run
        run: |
          echo "Running Nx release in dry-run mode..."
          npx nx release --dry-run --first-release --verbose 2>&1 | tee release-output.txt
          EXIT_CODE=${PIPESTATUS[0]}

          if [ $EXIT_CODE -ne 0 ]; then
            echo "❌ Nx release dry-run FAILED with exit code $EXIT_CODE"
            echo "release_status=failed" >> $GITHUB_OUTPUT
            exit $EXIT_CODE
          else
            echo "✅ Nx release dry-run SUCCEEDED"
            echo "release_status=success" >> $GITHUB_OUTPUT
          fi
        continue-on-error: false

      # Configure git for release commits
      - name: Configure git user
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Actual release on push (works for forks too)
      - name: Run Nx release (Push)
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Running Nx release..."
          npx nx release --first-release --verbose
        continue-on-error: false

  github-action-show-version:
    runs-on: ubuntu-latest
    name: Next version is
    if: github.event_name == 'pull_request'
    steps:
      - name: Publish a version comment
        uses: rvsia/github-action-show-version@v1.9alpha
        id: comment
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
